auto:        false
lsi:         false
server_port: 4567
pygments:    true
permalink:   none
markdown:    maruku
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex